http:
  port: ${PORT}
  host: ${HOST}
apiEndpoints:
  users:
    host: '*'
    paths: ['/api/users/*', '/cdn/*']
  jobs:
    host: '*'
    paths: ['/api/jobs/*']
  metadata:
    host: '*'
    paths: ['/api/metadata/*']
serviceEndpoints:
  jobs:
    url: 'http://localhost:3004'
  users:
    url: 'http://localhost:3002'
  metadata:
    url: 'http://localhost:3003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - auth
  - proxy
  - rate-limit

pipelines:
  users:
    apiEndpoints:
      - users
    policies:
      - cros:
          - action:
              - origin: '*'
      - auth:
      - proxy:
          - action:
              serviceEndpoint: users
              changeOrigin: true
  jobs:
    apiEndpoints:
      - jobs
    policies:
      - cros:
          - action:
              - origin: '*'
      - auth:
      - proxy:
          - action:
              serviceEndpoint: jobs
              changeOrigin: true
  metadata:
    apiEndpoints:
      - metadata
    policies:
      - cros:
          - action:
              - origin: '*'
      - auth:
      - proxy:
          - action:
              serviceEndpoint: metadata
              changeOrigin: true
